{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ee34ed86-3f25-4bd9-92d6-2584a15d8c4d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from datetime import datetime"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "85e978e4-67d1-414d-ad02-2236a767ec97",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load all raw files \n",
    "\n",
    "# KEYS.csv\n",
    "keys_df = pd.read_csv(\"KEYS.csv\")\n",
    "\n",
    "# CENSUS_MHI_STATE.csv\n",
    "mhi_df = pd.read_csv(\"CENSUS_MHI_STATE.csv\")\n",
    "\n",
    "# CENSUS_POPULATION_STATE.tsv\n",
    "population_df = pd.read_csv(\"CENSUS_POPULATION_STATE.tsv\", sep=\"\\t\")\n",
    "\n",
    "# REDFIN_MEDIAN_SALE_PRICE.csv\n",
    "redfin_df = pd.read_csv(\"REDFIN_MEDIAN_SALE_PRICE.csv\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2ffced6f-4f1e-4619-b249-2e52e6b98e00",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      key_row  census_msa\n",
      "0     alabama     Alabama\n",
      "1      alaska      Alaska\n",
      "2     arizona     Arizona\n",
      "3    arkansas    Arkansas\n",
      "4  california  California\n"
     ]
    }
   ],
   "source": [
    "# Step 2 : Setup a lookup column of States\n",
    "# Column A → key_row (keys_df.iloc[:, 0])\n",
    "# Column F → region_type or label (keys_df.iloc[:, 5])\n",
    "\n",
    "df_result = keys_df[\n",
    "    (keys_df.iloc[:, 5] == 'state') &\n",
    "    (~keys_df.iloc[:, 0].str.contains(\"'\", na=False))\n",
    "].copy()\n",
    "\n",
    "# Reset index and keep only key_row and census_msa (needed for lookups later)\n",
    "df_result = df_result.reset_index(drop=True)\n",
    "df_result = df_result[['key_row', 'census_msa']]\n",
    "\n",
    "# review result\n",
    "print(df_result.head())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9435ed12-74f1-489f-8c19-104d6c3434fa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      key_row  census_msa  census_population\n",
      "0     alabama     Alabama            5108468\n",
      "1      alaska      Alaska             733406\n",
      "2     arizona     Arizona            7431344\n",
      "3    arkansas    Arkansas            3067732\n",
      "4  california  California           38965193\n"
     ]
    }
   ],
   "source": [
    "# Step 3 : Define & Apply a function for population lookup  \n",
    "def get_census_population_for_key_row(key_row):\n",
    "    match_row = keys_df[keys_df['key_row'] == key_row]\n",
    "    if match_row.empty:\n",
    "        return None\n",
    "    census_msa = match_row.iloc[0]['census_msa']\n",
    "    col_name = f\"{census_msa}!!Estimate\"\n",
    "\n",
    "    pop_row = population_df[population_df[population_df.columns[0]].str.contains(\"Total population\", na=False)]\n",
    "    if pop_row.empty or col_name not in population_df.columns:\n",
    "        return None\n",
    "\n",
    "    value = pop_row.iloc[0][col_name]\n",
    "    if isinstance(value, str):\n",
    "        value = value.replace(',', '').strip()\n",
    "    try:\n",
    "        return int(value)\n",
    "    except:\n",
    "        return None\n",
    "\n",
    "# Apply the lookup for each key_row\n",
    "df_result['census_population'] = df_result['key_row'].apply(get_census_population_for_key_row)\n",
    "\n",
    "# review result\n",
    "print(df_result.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "1800578e-793d-4c2d-a9bc-d7922321ca9c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      key_row  census_msa  census_population population_rank\n",
      "0     alabama     Alabama            5108468            24th\n",
      "1      alaska      Alaska             733406            49th\n",
      "2     arizona     Arizona            7431344            14th\n",
      "3    arkansas    Arkansas            3067732            34th\n",
      "4  california  California           38965193             1st\n"
     ]
    }
   ],
   "source": [
    "# Step 4: Rank and format population \n",
    "def ordinal_suffix(rank):\n",
    "    if pd.isnull(rank):\n",
    "        return \"\"\n",
    "    rank = int(rank) \n",
    "    if 11 <= (rank % 100) <= 13:\n",
    "        return f\"{rank}th\"\n",
    "    else:\n",
    "        return f\"{rank}{['th', 'st', 'nd', 'rd', 'th', 'th', 'th', 'th', 'th', 'th'][rank % 10]}\"\n",
    "\n",
    "\n",
    "\n",
    "# Compute population rank (1 = highest)\n",
    "df_result['population_rank'] = df_result['census_population'].rank(ascending=False, method='min').astype(int)\n",
    "\n",
    "# Format as ordinal string\n",
    "df_result['population_rank'] = df_result['population_rank'].apply(ordinal_suffix)\n",
    "\n",
    "# Review result\n",
    "print(df_result.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "617a79ca-0f20-40ac-9e70-9e7899b13d94",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      key_row  census_msa  census_population population_rank  \\\n",
      "0     alabama     Alabama            5108468            24th   \n",
      "1      alaska      Alaska             733406            49th   \n",
      "2     arizona     Arizona            7431344            14th   \n",
      "3    arkansas    Arkansas            3067732            34th   \n",
      "4  california  California           38965193             1st   \n",
      "\n",
      "                                    population_blurb  \n",
      "0  Alabama is 24th in the nation in population am...  \n",
      "1  Alaska is 49th in the nation in population amo...  \n",
      "2  Arizona is 14th in the nation in population am...  \n",
      "3  Arkansas is 34th in the nation in population a...  \n",
      "4  California is 1st in the nation in population ...  \n"
     ]
    }
   ],
   "source": [
    "# Step 5: Create population_blurb using KEYS column H (alternative_name)\n",
    "# Load mapping of key_row -> alternative_name\n",
    "key_row_to_alt_name = keys_df.set_index('key_row')['alternative_name'].to_dict()\n",
    "\n",
    "df_result['population_blurb'] = df_result.apply(\n",
    "    lambda row: f\"{key_row_to_alt_name.get(row['key_row'], '')} is {row['population_rank']} in the nation in population among states, DC, and Puerto Rico.\",\n",
    "    axis=1\n",
    ")\n",
    "\n",
    "# Review result\n",
    "print(df_result.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "270e7cdd-bc08-4506-b64c-91310b14dc0f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      key_row  census_msa  census_population population_rank  \\\n",
      "0     alabama     Alabama            5108468            24th   \n",
      "1      alaska      Alaska             733406            49th   \n",
      "2     arizona     Arizona            7431344            14th   \n",
      "3    arkansas    Arkansas            3067732            34th   \n",
      "4  california  California           38965193             1st   \n",
      "\n",
      "                                    population_blurb  median_household_income  \n",
      "0  Alabama is 24th in the nation in population am...                    62027  \n",
      "1  Alaska is 49th in the nation in population amo...                    89336  \n",
      "2  Arizona is 14th in the nation in population am...                    76872  \n",
      "3  Arkansas is 34th in the nation in population a...                    58773  \n",
      "4  California is 1st in the nation in population ...                    96334  \n"
     ]
    }
   ],
   "source": [
    "# Step 6: Lookup median_household_income \n",
    "def get_income_for_key_row(key_row):\n",
    "    match_row = keys_df[keys_df['key_row'] == key_row]\n",
    "    if match_row.empty:\n",
    "        return None\n",
    "    census_msa = match_row.iloc[0]['census_msa']\n",
    "    col_name = f\"{census_msa}!!Median income (dollars)!!Estimate\"\n",
    "\n",
    "    income_row = mhi_df[mhi_df[mhi_df.columns[0]].str.contains(\"Households\", na=False)]\n",
    "    if income_row.empty or col_name not in mhi_df.columns:\n",
    "        return None\n",
    "\n",
    "    value = income_row.iloc[0][col_name]\n",
    "    if isinstance(value, str):\n",
    "        value = value.replace(',', '').replace('±', '').strip()\n",
    "    try:\n",
    "        return int(value)\n",
    "    except:\n",
    "        return None\n",
    "\n",
    "df_result['median_household_income'] = df_result['key_row'].apply(get_income_for_key_row)\n",
    "\n",
    "# Review result\n",
    "print(df_result.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "09fbdb40-3e03-4993-8136-8568d628a5de",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      key_row  census_msa  census_population population_rank  \\\n",
      "0     alabama     Alabama            5108468            24th   \n",
      "1      alaska      Alaska             733406            49th   \n",
      "2     arizona     Arizona            7431344            14th   \n",
      "3    arkansas    Arkansas            3067732            34th   \n",
      "4  california  California           38965193             1st   \n",
      "\n",
      "                                    population_blurb  median_household_income  \\\n",
      "0  Alabama is 24th in the nation in population am...                    62027   \n",
      "1  Alaska is 49th in the nation in population amo...                    89336   \n",
      "2  Arizona is 14th in the nation in population am...                    76872   \n",
      "3  Arkansas is 34th in the nation in population a...                    58773   \n",
      "4  California is 1st in the nation in population ...                    96334   \n",
      "\n",
      "  median_household_income_rank  \n",
      "0                         47th  \n",
      "1                         13th  \n",
      "2                         21st  \n",
      "3                         49th  \n",
      "4                          6th  \n"
     ]
    }
   ],
   "source": [
    "# Step 7: Rank Income & Add Ordinal Label\n",
    "df_result['median_household_income_rank'] = df_result['median_household_income'].rank(ascending=False, method='min').astype(int)\n",
    "df_result['median_household_income_rank'] = df_result['median_household_income_rank'].apply(ordinal_suffix)\n",
    "\n",
    "# Review result\n",
    "print(df_result.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "b07a6e3a-1e30-46d4-bb7f-b2c1f3316aa2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      key_row  census_msa  census_population population_rank  \\\n",
      "0     alabama     Alabama            5108468            24th   \n",
      "1      alaska      Alaska             733406            49th   \n",
      "2     arizona     Arizona            7431344            14th   \n",
      "3    arkansas    Arkansas            3067732            34th   \n",
      "4  california  California           38965193             1st   \n",
      "\n",
      "                                    population_blurb  median_household_income  \\\n",
      "0  Alabama is 24th in the nation in population am...                    62027   \n",
      "1  Alaska is 49th in the nation in population amo...                    89336   \n",
      "2  Arizona is 14th in the nation in population am...                    76872   \n",
      "3  Arkansas is 34th in the nation in population a...                    58773   \n",
      "4  California is 1st in the nation in population ...                    96334   \n",
      "\n",
      "  median_household_income_rank  \\\n",
      "0                         47th   \n",
      "1                         13th   \n",
      "2                         21st   \n",
      "3                         49th   \n",
      "4                          6th   \n",
      "\n",
      "                       median_household_income_blurb  \n",
      "0  Alabama is 47th in the nation in median househ...  \n",
      "1  Alaska is 13th in the nation in median househo...  \n",
      "2  Arizona is 21st in the nation in median househ...  \n",
      "3  Arkansas is 49th in the nation in median house...  \n",
      "4  California is 6th in the nation in median hous...  \n"
     ]
    }
   ],
   "source": [
    "# Step 8: Income blurb like:\n",
    "\n",
    "df_result['median_household_income_blurb'] = df_result.apply(\n",
    "    lambda row: (\n",
    "        f\"{key_row_to_alt_name.get(row['key_row'], '')} is \"\n",
    "        f\"{'the highest' if row['median_household_income_rank'] == '1st' else row['median_household_income_rank']} \"\n",
    "        \"in the nation in median household income among states, DC, and Puerto Rico.\"\n",
    "    ),\n",
    "    axis=1\n",
    ")\n",
    "\n",
    "# Review result\n",
    "print(df_result.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "9fb9d152-e868-4810-a595-86ab55217d26",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      key_row  census_msa  census_population population_rank  \\\n",
      "0     alabama     Alabama            5108468            24th   \n",
      "1      alaska      Alaska             733406            49th   \n",
      "2     arizona     Arizona            7431344            14th   \n",
      "3    arkansas    Arkansas            3067732            34th   \n",
      "4  california  California           38965193             1st   \n",
      "\n",
      "                                    population_blurb  median_household_income  \\\n",
      "0  Alabama is 24th in the nation in population am...                    62027   \n",
      "1  Alaska is 49th in the nation in population amo...                    89336   \n",
      "2  Arizona is 14th in the nation in population am...                    76872   \n",
      "3  Arkansas is 34th in the nation in population a...                    58773   \n",
      "4  California is 1st in the nation in population ...                    96334   \n",
      "\n",
      "  median_household_income_rank  \\\n",
      "0                         47th   \n",
      "1                         13th   \n",
      "2                         21st   \n",
      "3                         49th   \n",
      "4                          6th   \n",
      "\n",
      "                       median_household_income_blurb   state_key  \\\n",
      "0  Alabama is 47th in the nation in median househ...     alabama   \n",
      "1  Alaska is 13th in the nation in median househo...      alaska   \n",
      "2  Arizona is 21st in the nation in median househ...     arizona   \n",
      "3  Arkansas is 49th in the nation in median house...    arkansas   \n",
      "4  California is 6th in the nation in median hous...  california   \n",
      "\n",
      "   median_sale_price  \n",
      "0           283000.0  \n",
      "1           385000.0  \n",
      "2           456000.0  \n",
      "3           255000.0  \n",
      "4           833000.0  \n"
     ]
    }
   ],
   "source": [
    "# Step 9: Redfin Median Sale Price (latest month)\n",
    "\n",
    "# Prepare Redfin dataset\n",
    "redfin_data = redfin_df.copy()\n",
    "redfin_data.columns = redfin_data.iloc[0]  # Set first row as header\n",
    "redfin_data = redfin_data.iloc[1:]         # Remove header row\n",
    "\n",
    "# Get the latest available month (last column)\n",
    "price_columns = [col for col in redfin_data.columns if col and 'Region' not in str(col)]\n",
    "latest_month_col = price_columns[-1]\n",
    "\n",
    "# Clean and normalize\n",
    "redfin_data['state_key'] = redfin_data['Region'].str.strip().str.lower()\n",
    "redfin_data['latest_median_sale_price'] = (\n",
    "    redfin_data[latest_month_col]\n",
    "    .replace('[\\$,K]', '', regex=True)\n",
    "    .replace('', None)\n",
    "    .astype(float) * 1000\n",
    ")\n",
    "\n",
    "# Map sale price to each state\n",
    "state_price_dict = redfin_data.set_index('state_key')['latest_median_sale_price'].to_dict()\n",
    "df_result['state_key'] = df_result['key_row'].str.replace(\"_\", \" \").str.lower()\n",
    "df_result['median_sale_price'] = df_result['state_key'].map(state_price_dict)\n",
    "\n",
    "# Review result\n",
    "print(df_result.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "e6712560-47be-4a05-80da-80ea9fbad3df",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      key_row  census_msa  census_population population_rank  \\\n",
      "0     alabama     Alabama            5108468            24th   \n",
      "1      alaska      Alaska             733406            49th   \n",
      "2     arizona     Arizona            7431344            14th   \n",
      "3    arkansas    Arkansas            3067732            34th   \n",
      "4  california  California           38965193             1st   \n",
      "\n",
      "                                    population_blurb  median_household_income  \\\n",
      "0  Alabama is 24th in the nation in population am...                    62027   \n",
      "1  Alaska is 49th in the nation in population amo...                    89336   \n",
      "2  Arizona is 14th in the nation in population am...                    76872   \n",
      "3  Arkansas is 34th in the nation in population a...                    58773   \n",
      "4  California is 1st in the nation in population ...                    96334   \n",
      "\n",
      "  median_household_income_rank  \\\n",
      "0                         47th   \n",
      "1                         13th   \n",
      "2                         21st   \n",
      "3                         49th   \n",
      "4                          6th   \n",
      "\n",
      "                       median_household_income_blurb   state_key  \\\n",
      "0  Alabama is 47th in the nation in median househ...     alabama   \n",
      "1  Alaska is 13th in the nation in median househo...      alaska   \n",
      "2  Arizona is 21st in the nation in median househ...     arizona   \n",
      "3  Arkansas is 49th in the nation in median house...    arkansas   \n",
      "4  California is 6th in the nation in median hous...  california   \n",
      "\n",
      "   median_sale_price median_sale_price_rank  median_sale_price_rank_int  \n",
      "0           283000.0                   36th                          36  \n",
      "1           385000.0                   22nd                          22  \n",
      "2           456000.0                   16th                          16  \n",
      "3           255000.0                   42nd                          42  \n",
      "4           833000.0                    1st                           1  \n"
     ]
    }
   ],
   "source": [
    "# Step 10: Rank and format median sale price\n",
    "valid_prices = df_result['median_sale_price'].notnull()\n",
    "df_result.loc[valid_prices, 'median_sale_price_rank'] = (\n",
    "    df_result.loc[valid_prices, 'median_sale_price']\n",
    "    .rank(ascending=False, method='min')\n",
    ")\n",
    "\n",
    "df_result['median_sale_price_rank_int'] = df_result['median_sale_price_rank'].round().astype('Int64')\n",
    "df_result['median_sale_price_rank'] = df_result['median_sale_price_rank_int'].apply(\n",
    "    lambda x: ordinal_suffix(x) if pd.notnull(x) else ''\n",
    ")\n",
    "\n",
    "# Review result\n",
    "print(df_result.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "346a9acf-a1ac-4e00-832c-e4f2c54d04a8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      key_row  census_msa  census_population population_rank  \\\n",
      "0     alabama     Alabama            5108468            24th   \n",
      "1      alaska      Alaska             733406            49th   \n",
      "2     arizona     Arizona            7431344            14th   \n",
      "3    arkansas    Arkansas            3067732            34th   \n",
      "4  california  California           38965193             1st   \n",
      "\n",
      "                                    population_blurb  median_household_income  \\\n",
      "0  Alabama is 24th in the nation in population am...                    62027   \n",
      "1  Alaska is 49th in the nation in population amo...                    89336   \n",
      "2  Arizona is 14th in the nation in population am...                    76872   \n",
      "3  Arkansas is 34th in the nation in population a...                    58773   \n",
      "4  California is 1st in the nation in population ...                    96334   \n",
      "\n",
      "  median_household_income_rank  \\\n",
      "0                         47th   \n",
      "1                         13th   \n",
      "2                         21st   \n",
      "3                         49th   \n",
      "4                          6th   \n",
      "\n",
      "                       median_household_income_blurb   state_key  \\\n",
      "0  Alabama is 47th in the nation in median househ...     alabama   \n",
      "1  Alaska is 13th in the nation in median househo...      alaska   \n",
      "2  Arizona is 21st in the nation in median househ...     arizona   \n",
      "3  Arkansas is 49th in the nation in median house...    arkansas   \n",
      "4  California is 6th in the nation in median hous...  california   \n",
      "\n",
      "   median_sale_price median_sale_price_rank  median_sale_price_rank_int  \\\n",
      "0           283000.0                   36th                          36   \n",
      "1           385000.0                   22nd                          22   \n",
      "2           456000.0                   16th                          16   \n",
      "3           255000.0                   42nd                          42   \n",
      "4           833000.0                    1st                           1   \n",
      "\n",
      "                             median_sale_price_blurb  \n",
      "0  Alabama has the 36th highest median sale price...  \n",
      "1  Alaska has the 22nd highest median sale price ...  \n",
      "2  Arizona has the 16th highest median sale price...  \n",
      "3  Arkansas has the 42nd highest median sale pric...  \n",
      "4  California has the single highest median sale ...  \n"
     ]
    }
   ],
   "source": [
    "# Step 11: Sale Price Blurb \n",
    "# Parse Redfin column name as Month Year\n",
    "\n",
    "try:\n",
    "    latest_date_obj = pd.to_datetime(latest_month_col, errors='coerce')\n",
    "    formatted_month_year = latest_date_obj.strftime(\"%B %Y\") if not pd.isnull(latest_date_obj) else latest_month_col\n",
    "except:\n",
    "    formatted_month_year = latest_month_col\n",
    "\n",
    "# Now create the blurb using the rank column\n",
    "df_result['median_sale_price_blurb'] = df_result.apply(\n",
    "    lambda row: (\n",
    "        f\"{key_row_to_alt_name.get(row['key_row'], '')} has the \"\n",
    "        f\"{'single' if row['median_sale_price_rank'] == '1st' else row['median_sale_price_rank']} \"\n",
    "        f\"highest median sale price on homes in the nation among states, DC, and Puerto Rico, \"\n",
    "        f\"according to Redfin data from {formatted_month_year}.\"\n",
    "    ),\n",
    "    axis=1\n",
    ")\n",
    "\n",
    "# Review result\n",
    "print(df_result.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "c05ec4a2-69ee-45a0-8082-db69a46bc91b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      key_row  census_msa  census_population population_rank  \\\n",
      "0     alabama     Alabama            5108468            24th   \n",
      "1      alaska      Alaska             733406            49th   \n",
      "2     arizona     Arizona            7431344            14th   \n",
      "3    arkansas    Arkansas            3067732            34th   \n",
      "4  california  California           38965193             1st   \n",
      "\n",
      "                                    population_blurb  median_household_income  \\\n",
      "0  Alabama is 24th in the nation in population am...                    62027   \n",
      "1  Alaska is 49th in the nation in population amo...                    89336   \n",
      "2  Arizona is 14th in the nation in population am...                    76872   \n",
      "3  Arkansas is 34th in the nation in population a...                    58773   \n",
      "4  California is 1st in the nation in population ...                    96334   \n",
      "\n",
      "  median_household_income_rank  \\\n",
      "0                         47th   \n",
      "1                         13th   \n",
      "2                         21st   \n",
      "3                         49th   \n",
      "4                          6th   \n",
      "\n",
      "                       median_household_income_blurb   state_key  \\\n",
      "0  Alabama is 47th in the nation in median househ...     alabama   \n",
      "1  Alaska is 13th in the nation in median househo...      alaska   \n",
      "2  Arizona is 21st in the nation in median househ...     arizona   \n",
      "3  Arkansas is 49th in the nation in median house...    arkansas   \n",
      "4  California is 6th in the nation in median hous...  california   \n",
      "\n",
      "   median_sale_price median_sale_price_rank  median_sale_price_rank_int  \\\n",
      "0           283000.0                   36th                          36   \n",
      "1           385000.0                   22nd                          22   \n",
      "2           456000.0                   16th                          16   \n",
      "3           255000.0                   42nd                          42   \n",
      "4           833000.0                    1st                           1   \n",
      "\n",
      "                             median_sale_price_blurb  \\\n",
      "0  Alabama has the 36th highest median sale price...   \n",
      "1  Alaska has the 22nd highest median sale price ...   \n",
      "2  Arizona has the 16th highest median sale price...   \n",
      "3  Arkansas has the 42nd highest median sale pric...   \n",
      "4  California has the single highest median sale ...   \n",
      "\n",
      "   house_affordability_ratio  \n",
      "0                        4.6  \n",
      "1                        4.3  \n",
      "2                        5.9  \n",
      "3                        4.3  \n",
      "4                        8.6  \n"
     ]
    }
   ],
   "source": [
    "# Step 12: Calculate house affordability ratio\n",
    "\n",
    "df_result['house_affordability_ratio'] = (\n",
    "    df_result['median_sale_price'] / df_result['median_household_income']\n",
    ").round(1)\n",
    "\n",
    "# Review result\n",
    "print(df_result.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "dad1b811-ce61-4294-9ca5-65acd04c281e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      key_row  census_msa  census_population population_rank  \\\n",
      "0     alabama     Alabama            5108468            24th   \n",
      "1      alaska      Alaska             733406            49th   \n",
      "2     arizona     Arizona            7431344            14th   \n",
      "3    arkansas    Arkansas            3067732            34th   \n",
      "4  california  California           38965193             1st   \n",
      "\n",
      "                                    population_blurb  median_household_income  \\\n",
      "0  Alabama is 24th in the nation in population am...                    62027   \n",
      "1  Alaska is 49th in the nation in population amo...                    89336   \n",
      "2  Arizona is 14th in the nation in population am...                    76872   \n",
      "3  Arkansas is 34th in the nation in population a...                    58773   \n",
      "4  California is 1st in the nation in population ...                    96334   \n",
      "\n",
      "  median_household_income_rank  \\\n",
      "0                         47th   \n",
      "1                         13th   \n",
      "2                         21st   \n",
      "3                         49th   \n",
      "4                          6th   \n",
      "\n",
      "                       median_household_income_blurb   state_key  \\\n",
      "0  Alabama is 47th in the nation in median househ...     alabama   \n",
      "1  Alaska is 13th in the nation in median househo...      alaska   \n",
      "2  Arizona is 21st in the nation in median househ...     arizona   \n",
      "3  Arkansas is 49th in the nation in median house...    arkansas   \n",
      "4  California is 6th in the nation in median hous...  california   \n",
      "\n",
      "   median_sale_price median_sale_price_rank  median_sale_price_rank_int  \\\n",
      "0           283000.0                   36th                          36   \n",
      "1           385000.0                   22nd                          22   \n",
      "2           456000.0                   16th                          16   \n",
      "3           255000.0                   42nd                          42   \n",
      "4           833000.0                    1st                           1   \n",
      "\n",
      "                             median_sale_price_blurb  \\\n",
      "0  Alabama has the 36th highest median sale price...   \n",
      "1  Alaska has the 22nd highest median sale price ...   \n",
      "2  Arizona has the 16th highest median sale price...   \n",
      "3  Arkansas has the 42nd highest median sale pric...   \n",
      "4  California has the single highest median sale ...   \n",
      "\n",
      "   house_affordability_ratio house_affordability_ratio_rank  \\\n",
      "0                        4.6                           24th   \n",
      "1                        4.3                           18th   \n",
      "2                        5.9                           38th   \n",
      "3                        4.3                           18th   \n",
      "4                        8.6                           50th   \n",
      "\n",
      "   house_affordability_ratio_rank_int  \n",
      "0                                  24  \n",
      "1                                  18  \n",
      "2                                  38  \n",
      "3                                  18  \n",
      "4                                  50  \n"
     ]
    }
   ],
   "source": [
    "# Step 13: Rank the house affordability ratio\n",
    "\n",
    "\n",
    "# Only rank rows with valid affordability ratios\n",
    "valid_afford = df_result['house_affordability_ratio'].notnull()\n",
    "\n",
    "# Calculate ascending rank (1 = most affordable)\n",
    "df_result.loc[valid_afford, 'house_affordability_ratio_rank'] = (\n",
    "    df_result.loc[valid_afford, 'house_affordability_ratio']\n",
    "    .rank(ascending=True, method='min')\n",
    ")\n",
    "\n",
    "# Keep as Int64 to allow for missing values\n",
    "df_result['house_affordability_ratio_rank_int'] = (\n",
    "    df_result['house_affordability_ratio_rank'].round().astype('Int64')\n",
    ")\n",
    "\n",
    "df_result['house_affordability_ratio_rank'] = df_result[\n",
    "    'house_affordability_ratio_rank_int'\n",
    "].apply(ordinal_suffix)\n",
    "\n",
    "# Review result\n",
    "print(df_result.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "57c8aa60-2e83-4891-848a-59c384e14564",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      key_row  census_msa  census_population population_rank  \\\n",
      "0     alabama     Alabama            5108468            24th   \n",
      "1      alaska      Alaska             733406            49th   \n",
      "2     arizona     Arizona            7431344            14th   \n",
      "3    arkansas    Arkansas            3067732            34th   \n",
      "4  california  California           38965193             1st   \n",
      "\n",
      "                                    population_blurb  median_household_income  \\\n",
      "0  Alabama is 24th in the nation in population am...                    62027   \n",
      "1  Alaska is 49th in the nation in population amo...                    89336   \n",
      "2  Arizona is 14th in the nation in population am...                    76872   \n",
      "3  Arkansas is 34th in the nation in population a...                    58773   \n",
      "4  California is 1st in the nation in population ...                    96334   \n",
      "\n",
      "  median_household_income_rank  \\\n",
      "0                         47th   \n",
      "1                         13th   \n",
      "2                         21st   \n",
      "3                         49th   \n",
      "4                          6th   \n",
      "\n",
      "                       median_household_income_blurb   state_key  \\\n",
      "0  Alabama is 47th in the nation in median househ...     alabama   \n",
      "1  Alaska is 13th in the nation in median househo...      alaska   \n",
      "2  Arizona is 21st in the nation in median househ...     arizona   \n",
      "3  Arkansas is 49th in the nation in median house...    arkansas   \n",
      "4  California is 6th in the nation in median hous...  california   \n",
      "\n",
      "   median_sale_price median_sale_price_rank  median_sale_price_rank_int  \\\n",
      "0           283000.0                   36th                          36   \n",
      "1           385000.0                   22nd                          22   \n",
      "2           456000.0                   16th                          16   \n",
      "3           255000.0                   42nd                          42   \n",
      "4           833000.0                    1st                           1   \n",
      "\n",
      "                             median_sale_price_blurb  \\\n",
      "0  Alabama has the 36th highest median sale price...   \n",
      "1  Alaska has the 22nd highest median sale price ...   \n",
      "2  Arizona has the 16th highest median sale price...   \n",
      "3  Arkansas has the 42nd highest median sale pric...   \n",
      "4  California has the single highest median sale ...   \n",
      "\n",
      "   house_affordability_ratio house_affordability_ratio_rank  \\\n",
      "0                        4.6                           24th   \n",
      "1                        4.3                           18th   \n",
      "2                        5.9                           38th   \n",
      "3                        4.3                           18th   \n",
      "4                        8.6                           50th   \n",
      "\n",
      "   house_affordability_ratio_rank_int  \\\n",
      "0                                  24   \n",
      "1                                  18   \n",
      "2                                  38   \n",
      "3                                  18   \n",
      "4                                  50   \n",
      "\n",
      "                     house_affordability_ratio_blurb  \n",
      "0  Alabama has the 24th lowest house affordabilit...  \n",
      "1  Alaska has the 18th lowest house affordability...  \n",
      "2  Arizona has the 38th lowest house affordabilit...  \n",
      "3  Arkansas has the 18th lowest house affordabili...  \n",
      "4  California has the 50th lowest house affordabi...  \n"
     ]
    }
   ],
   "source": [
    "# Step 14: Affordability Ratio Blurb \n",
    "\n",
    "# Build the affordability blurb\n",
    "df_result['house_affordability_ratio_blurb'] = df_result.apply(\n",
    "    lambda row: (\n",
    "        f\"{key_row_to_alt_name.get(row['key_row'], '')} has the \"\n",
    "        f\"{'single' if row['house_affordability_ratio_rank'] == '1st' else row['house_affordability_ratio_rank']} \"\n",
    "        f\"lowest house affordability ratio in the nation among states, DC, and Puerto Rico, \"\n",
    "        f\"according to Redfin data from {formatted_month_year}.\"\n",
    "    ),\n",
    "    axis=1\n",
    ")\n",
    "\n",
    "# Review result\n",
    "print(df_result.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "d10bfa72-f79b-4eaa-b985-579a390eabfc",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Format census_population with commas (e.g., 5,108,468)\n",
    "df_result['census_population'] = df_result['census_population'].apply(\n",
    "    lambda x: f\"{int(x):,}\" if pd.notnull(x) else \"\"\n",
    ")\n",
    "\n",
    "# Format median_household_income with $ and commas (e.g., $96,334)\n",
    "df_result['median_household_income'] = df_result['median_household_income'].apply(\n",
    "    lambda x: f\"${int(x):,}\" if pd.notnull(x) else \"\"\n",
    ")\n",
    "\n",
    "# Format median_sale_price with $ and commas (e.g., $833,000)\n",
    "df_result['median_sale_price'] = df_result['median_sale_price'].apply(\n",
    "    lambda x: f\"${int(x):,}\" if pd.notnull(x) else \"\"\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "81e8e4b9-06dc-400c-b3e9-fcf30f4e1b2b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Final Export \n",
    "final_columns = ['key_row','census_population','population_rank','population_blurb', 'median_household_income', 'median_household_income_rank', 'median_household_income_blurb', 'median_sale_price','median_sale_price_rank', 'median_sale_price_blurb','house_affordability_ratio','house_affordability_ratio_rank','house_affordability_ratio_blurb']\n",
    "final_csv_df = df_result[final_columns]\n",
    "final_csv_df.to_csv(\"final_state_analysis.csv\", index=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "cf0751ff-b955-486c-aceb-177fe0d28009",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Optional Visualizations\n",
    "\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# Load the final CSV \n",
    "df = pd.read_csv(\"final_state_analysis.csv\")\n",
    "\n",
    "# Optional: remove $ and commas to convert numeric columns back\n",
    "df['median_sale_price'] = df['median_sale_price'].replace('[\\$,]', '', regex=True).astype(float)\n",
    "df['median_household_income'] = df['median_household_income'].replace('[\\$,]', '', regex=True).astype(float)\n",
    "df['census_population'] = df['census_population'].replace(',', '', regex=True).astype(int)\n",
    "df['house_affordability_ratio'] = pd.to_numeric(df['house_affordability_ratio'], errors='coerce')\n",
    "\n",
    "# 1. Top 10 states by population\n",
    "top_pop = df.sort_values(by='census_population', ascending=False).head(10)\n",
    "plt.figure(figsize=(10, 6))\n",
    "sns.barplot(x='census_population', y='key_row', data=top_pop, palette='Blues_d')\n",
    "plt.title(\"Top 10 States by Population\")\n",
    "plt.xlabel(\"Population\")\n",
    "plt.ylabel(\"State\")\n",
    "plt.tight_layout()\n",
    "plt.savefig(\"top_10_population.png\")\n",
    "plt.close()\n",
    "\n",
    "# 2. Top 10 states by median sale price\n",
    "top_price = df.sort_values(by='median_sale_price', ascending=False).head(10)\n",
    "plt.figure(figsize=(10, 6))\n",
    "sns.barplot(x='median_sale_price', y='key_row', data=top_price, palette='Reds_d')\n",
    "plt.title(\"Top 10 States by Median Sale Price\")\n",
    "plt.xlabel(\"Median Sale Price ($)\")\n",
    "plt.ylabel(\"State\")\n",
    "plt.tight_layout()\n",
    "plt.savefig(\"top_10_sale_price.png\")\n",
    "plt.close()\n",
    "\n",
    "# 3. Top 10 most affordable states (lowest affordability ratio)\n",
    "most_affordable = df.sort_values(by='house_affordability_ratio').head(10)\n",
    "plt.figure(figsize=(10, 6))\n",
    "sns.barplot(x='house_affordability_ratio', y='key_row', data=most_affordable, palette='Greens_d')\n",
    "plt.title(\"Top 10 Most Affordable States\")\n",
    "plt.xlabel(\"Affordability Ratio\")\n",
    "plt.ylabel(\"State\")\n",
    "plt.tight_layout()\n",
    "plt.savefig(\"most_affordable_states.png\")\n",
    "plt.close()\n",
    "\n",
    "# 4. Scatter plot: Income vs. Home Price\n",
    "plt.figure(figsize=(8, 6))\n",
    "sns.scatterplot(x='median_household_income', y='median_sale_price', data=df)\n",
    "plt.title(\"Median Household Income vs. Median Sale Price\")\n",
    "plt.xlabel(\"Median Household Income ($)\")\n",
    "plt.ylabel(\"Median Sale Price ($)\")\n",
    "plt.tight_layout()\n",
    "plt.savefig(\"income_vs_sale_price.png\")\n",
    "plt.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "871ee070-bc7a-4399-83d9-afb9814afe6a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "anaconda-2024.02-py310",
   "language": "python",
   "name": "conda-env-anaconda-2024.02-py310-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
